const fs = require('fs');
const lines = ["exec(open('helper2.py').read())", ''];
const add = (f, ops) => {
  const s = ops.map(op => '    (' + op.map(p => typeof p === 'number' ? p : JSON.stringify(p)).join(',') + ')').join(',\n');
  lines.push('fix(' + JSON.stringify(f) + ',[', s, '])', '');
};
add('add_dtmf_collection_complete.js',[['rf',80,'function deleteFlow(','function _deleteFlow(']]);
add('add_india_decision_via_api.js',[['rc',20,'e','_e'],['rc',294,'error','_error']]);
add('add_india_routing_decision.js',[['rc',19,'e','_e'],['rf',71,'function checkoutFlow(','function _checkoutFlow('],['rf',88,'function updateFlow(','function _updateFlow('],['rv',93,'const mainActions','const _mainActions'],['rv',98,'const decisionAction','const _decisionAction']]);
add('auto_complete_geo_routing.js',[['rc',37,'e','_e'],['rv',43,'const flowWithConfig','const _flowWithConfig'],['rc',131,'archyError','_archyError']]);
add('auto_create_cogflow_browser.js',[['rv',18,'const FLOW_CONFIG','const _FLOW_CONFIG'],['rv',195,'const createButtonSelector','const _createButtonSelector'],['rc',248,'error','_error']]);
add('auto_publish_browser.js',[['rc',162,'e','_e']]);
add('automate_flow_config.js',[['rc',21,'e','_e']]);
add('build_claude_cars32_complete.js',[['rc',73,'deleteError','_deleteError']]);
add('check_flow_api.js',[['rc',31,'e','_e'],['rc',73,'error','_error']]);
add('claude_cars_complete_setup.js',[['rc',35,'e','_e'],['rc',81,'e','_e']]);
add('complete_claude_cars23_flow.js',[['dl',2]]);
add('complete_flow_setup_final.js',[['rc',35,'e','_e'],['rc',335,'error','_error'],['rv',419,'const verifiedFlow','const _verifiedFlow']]);
add('complete_inqueue_publishing.js',[['rc',93,'flows','_flows']]);
add('configure_and_publish_claude_cars.js',[['rv',563,'const updatedFlow','const _updatedFlow'],['rv',569,'const savedConfig','const _savedConfig']]);
add('configure_and_publish_flow.js',[['rc',19,'e','_e'],['rc',124,'error','_error']]);
add('configure_flow_complete.js',[['rc',19,'e','_e'],['rc',121,'error','_error']]);
add('create_accessible_flow.js',[['rc',21,'e','_e']]);
add('create_and_export_claude_cars.js',[['rc',51,'e','_e'],['rc',62,'e','_e'],['rc',106,'e','_e']]);
add('create_claude_cars23_final.js',[['rc',91,'e','_e']]);
add('create_claude_cars_complete.js',[['rc',22,'e','_e'],['rc',110,'e','_e'],['rc',155,'e','_e']]);
add('create_claude_cars_flow_complete.js',[['rc',55,'e','_e'],['rc',65,'e','_e']]);
add('create_claude_cars_queues.js',[['rc',18,'e','_e']]);
add('create_complete_flow.js',[['rc',87,'e','_e']]);
add('create_genesys_flow.js',[['rc',34,'e','_e']]);
add('create_india_inqueue_flow.js',[['rc',19,'e','_e']]);
add('create_new_flow_fresh.js',[['rc',36,'e','_e']]);
add('create_testflow_claude.js',[['rc',16,'e','_e']]);
add('create_testflow_claude_vj123456.js',[['rc',34,'e','_e']]);
add('create_testflow_vj123.js',[['rc',20,'e','_e']]);
add('create_testflow_vj123456.js',[['rc',29,'e','_e']]);
add('delete_and_rename_flow.js',[['rc',30,'e','_e']]);
add('export_final_flow.js',[['rc',17,'e','_e']]);
add('export_flow_to_i3.js',[['rc',29,'e','_e']]);
add('find_and_update_flow.js',[['rc',19,'e','_e']]);
add('fix_genesys_flow.js',[['rc',31,'e','_e']]);
add('genesys-flow-tool.js',[['rc',52,'e','_e']]);
add('get_flow_template.js',[['rc',31,'e','_e']]);
add('import_complete_flow.js',[['rc',28,'e','_e']]);
add('import_i3_file.js',[['rc',28,'e','_e']]);
add('list_all_flows.js',[['rc',18,'e','_e']]);
add('recreate_flow.js',[['rc',16,'e','_e']]);
add('recreate_testflow_claude_properly.js',[['rc',35,'e','_e']]);
add('rename_flow_only.js',[['rc',30,'e','_e']]);
add('unlock_and_recreate_flow.js',[['rc',35,'e','_e']]);
add('update_existing_flow.js',[['rc',31,'e','_e']]);
add('update_flow_division.js',[['rc',26,'e','_e']]);
add('update_flow_with_proper_config.js',[['rc',35,'e','_e']]);
add('update_genesys_flow_division.js',[['rc',34,'e','_e']]);
add('update_testflow_vj123456.js',[['rc',17,'e','_e']]);
add('verify_claude_cars_flow.js',[['rc',18,'e','_e']]);
add('complete_automation.js',[['dl',2],['rc',22,'e','_e'],['rf',36,'function authenticate(','function _authenticate('],['rf',57,'function deleteFlow(','function _deleteFlow('],['rc',73,'error','_error'],['rf',79,'function getDivisionId(','function _getDivisionId('],['rf',95,'function createNewFlow(','function _createNewFlow(']]);
add('complete_claude_cars32_automation.js',[['dl',3],['rc',107,'error','_error']]);
add('create_and_publish_claude_cars1.js',[['rc',62,'error','_error'],['rv',106,'const currentFlow','const _currentFlow'],['rc',155,'execError','_execError'],['rc',234,'valError','_valError'],['rc',281,'unlockError','_unlockError'],['rv',375,'const published','const _published']]);
add('create_and_publish_claude_cars32.js',[['dl',2],['rf',96,'function createFlowConfig(','function _createFlowConfig('],['rc',430,'queueIds','_queueIds'],['sa',481,'result']]);
add('create_and_publish_claude_cars_api.js',[['dl',2],['dl',3],['rf',169,'function publishFlow(','function _publishFlow('],['rc',227,'error','_error']]);
add('create_claude_cars23_complete.js',[['rc',77,'e','_e'],['rc',121,'e','_e'],['rv',388,'const validation','const _validation']]);
add('create_claude_cars32_direct_api.js',[['rc',566,'deleteError','_deleteError'],['rv',571,'const isNewFlow','const _isNewFlow'],['sa',603,'checkinResponse']]);
add('create_claude_flow_with_requirements.js',[['rc',31,'e','_e'],['rc',168,'error','_error']]);
add('create_complete_working_flow.js',[['rc',37,'e','_e'],['rc',183,'error','_error']]);
add('create_flow_from_yaml.js',[['rc',37,'e','_e'],['rc',104,'error','_error'],['rc',125,'error','_error']]);
add('create_full_flow_properly.js',[['rc',36,'e','_e'],['rc',168,'error','_error'],['sa',388,'result'],['sa',401,'result']]);
add('create_inqueue_flows_api.js',[['rc',18,'e','_e'],['rv',71,'greeting','_greeting'],['rv',71,'loopMessage','_loopMessage']]);
add('create_minimal_valid_flow.js',[['rc',31,'e','_e'],['rc',118,'error','_error']]);
add('create_simple_sample_flow.js',[['rv',130,'result','_result'],['rv',130,'version','_version']]);
add('create_simple_valid_flow.js',[['rc',31,'e','_e'],['rc',132,'error','_error']]);
add('create_testflow_ready.js',[['rc',37,'e','_e'],['rc',192,'queueId','_queueId']]);
add('export_and_update_flow.js',[['rf',77,'function getFlowLatestConfig(','function _getFlowLatestConfig('],['rv',234,'const publishResult','const _publishResult']]);
add('final_claude_cars32_builder.js',[['rc',71,'deleteError','_deleteError'],['rv',250,'const flowDetails','const _flowDetails']]);
add('final_complete_working_flow.js',[['rc',22,'e','_e'],['rv',81,'const queue','const _queue'],['rc',154,'e','_e'],['rc',174,'e','_e']]);
add('final_publish_attempt.js',[['rv',101,'version','_version'],['rv',101,'success','_success']]);
add('final_working_flow_setup.js',[['rv',13,'const QUEUE_NAME','const _QUEUE_NAME'],['rc',29,'e','_e'],['rc',103,'error','_error']]);
add('find_your_flow.js',[['rc',20,'e','_e'],['rc',82,'error','_error'],['rv',104,'const flowsByName','const _flowsByName']]);
add('force_auto_publish.js',[['rv',84,'const yamlContent','const _yamlContent'],['rc',110,'publishErr','_publishErr']]);
add('full_automation_attempt.js',[['rc',22,'e','_e'],['rc',91,'error','_error'],['rc',312,'error','_error']]);
add('import_and_publish_yaml_now.js',[['rf',95,'function updateFlowFromYAML(','function _updateFlowFromYAML('],['rc',223,'publishError','_publishError']]);
add('import_claude_cars32_yaml.js',[['dl',3]]);
add('import_flow_via_api.js',[['rc',32,'e','_e'],['rc',101,'error','_error']]);
add('import_flow_with_config.js',[['rc',35,'e','_e'],['rc',112,'error','_error'],['rc',144,'error','_error'],['rc',168,'error','_error'],['rc',219,'queueId','_queueId']]);
add('import_i3_flow_direct.js',[['rc',31,'e','_e'],['rc',125,'error','_error'],['rv',159,'const flowData','const _flowData']]);
add('import_testflow_vj123456.js',[['dl',3],['rv',8,'const I3_FILE','const _I3_FILE'],['rc',19,'e','_e'],['rv',100,'const flow','const _flow']]);
add('publish_archy_test.js',[['dl',2],['rc',114,'err','_err']]);
add('publish_claude_cars.js',[['rc',18,'e','_e'],['rv',61,'const token','const _token']]);
add('publish_claude_cars1.js',[['dl',2],['rv',21,'const output','const _output'],['rc',29,'error','_error'],['rv',41,'const output','const _output'],['rc',49,'error','_error'],['rv',61,'const output','const _output'],['rc',69,'error','_error']]);
add('publish_claude_cars1_correct.js',[['rv',31,'const output','const _output']]);
add('publish_claude_cars_flows.js',[['rc',53,'err','_err'],['rc',113,'err','_err'],['rc',173,'err','_err']]);
add('publish_empty_inqueue_flows.js',[['rc',22,'e','_e']]);
add('publish_existing_flow.js',[['rc',34,'fullFlow','_fullFlow']]);
add('publish_flow_with_sdk.js',[['rc',40,'err','_err'],['rv',62,'const updatedConfig','const _updatedConfig']]);
add('publish_testflow_claude.js',[['rc',17,'e','_e']]);
add('recreate_and_publish_clean.js',[['rc',32,'err','_err'],['rc',158,'err1','_err1']]);
add('recreate_archy_test.js',[['rc',37,'err','_err'],['rc',159,'publishResult','_publishResult']]);
add('run_cogflow_automation_now.js',[['rc',61,'e','_e'],['rc',78,'e','_e'],['rc',89,'e','_e'],['rc',102,'e','_e'],['rc',131,'e','_e'],['rc',145,'e','_e'],['rc',162,'e','_e'],['rc',203,'installError','_installError']]);
add('setup_complete_flow.js',[['rc',21,'e','_e'],['rc',106,'error','_error']]);
add('update_claude_cars1_with_geo_routing_api.js',[['rv',7,'const QUEUE_ID','const _QUEUE_ID']]);
add('update_existing_unlocked_flow.js',[['rc',22,'e','_e'],['rc',121,'e','_e']]);
add('update_flow_configuration.js',[['rc',78,'e','_e'],['rv',158,'const result','const _result']]);
add('update_flow_with_dtmf_menu.js',[['rf',79,'function checkoutFlow(','function _checkoutFlow('],['rf',112,'function updateFlow(','function _updateFlow('],['rf',147,'function checkinFlow(','function _checkinFlow('],['rf',179,'function publishFlow(','function _publishFlow(']]);
add('upload_claude_cars23.js',[['dl',1]]);
add('validate_setup.js',[['rv',14,'reject','_reject'],['rc',20,'e','_e']]);
add('verify_oauth_and_publish.js',[['rc',164,'error','_error'],['rc',174,'error','_error'],['rv',181,'const userInfo','const _userInfo'],['rc',184,'error','_error']]);
add('auto_publish_all_flows.js',[['dl',3],['sa',51,'result'],['rc',55,'err','_err'],['sa',60,'version'],['rc',64,'err2','_err2'],['sa',96,'result'],['rc',100,'err','_err'],['sa',104,'version'],['rc',108,'err2','_err2'],['sa',140,'result'],['rc',144,'err','_err'],['sa',148,'version'],['rc',152,'err2','_err2'],['sa',211,'result'],['rc',215,'err','_err'],['sa',219,'version'],['rc',223,'err2','_err2']]);
lines.push('print("All fixes done!")');
fs.writeFileSync('C:/Users/VijayBandaru/run_fixes.py', lines.join('\n'));
console.log('run_fixes.py written, fix calls:', (lines.filter(l => l.startsWith('fix('))).length);
